config/routes.rb
Rails.application.routes.draw do

  get 'contact' => 'pages#contact'
  
  get 'about' => 'pages#about'
  
  get 'help' => 'pages#help'
  
  get 'signup' => 'users#new'
  
  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contacts"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Signup"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "Ruby on Rails Tutorials"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    logo = image_tag "logo.png", :alt => "logo", :class => "round"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contacts", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
</ul> 
</nav>
</footer>

app/views/layouts/_header.html.erb
	<header>
		<%= logo %>
		<nav>
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Sign in", '#' %></li>
			</ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> 
	<![endif]-->
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %> 
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]--> 
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets'%>
</head>
<body>
<div class="container">
	<%= render 'layouts/header' %>
	<section class="round">
		<%= yield %>
	</section>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>I am empty inside</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Don't come crying to us for small things resolve on its own</p> 

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p>
<%= link_to 'Signup', signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>